repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.14

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.17.0
    hooks:
      - id: eslint
        files: '\.(js|jsx)$'
        args: ["--config", "eslint.config.mjs"]

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.4
    hooks:
      - id: actionlint

  - repo: local
    hooks:
      - id: translations
        name: translations
        entry: make translations
        language: system
        files: '\.py$|\.html$|babel\.cfg$'
        pass_filenames: false

      - id: reformat
        name: reformat
        entry: make reformat
        language: system
        files: '\.py$|\.html$'
        pass_filenames: false

      - id: lint
        name: lint
        entry: make lint
        language: system
        files: '\.py$|\.js$'
        pass_filenames: false
