[mypy]
python_version = 3.14
warn_unreachable = True
warn_unused_configs = True
warn_unused_ignores = True
plugins = mypy_zope:plugin
exclude = warehouse/locale/.*|warehouse/migrations/versions.*
cache_dir = .cache/mypy

[mypy-bpython.*]
ignore_missing_imports = True

[mypy-b2sdk.*]
ignore_missing_imports = True

[mypy-celery.app.backends.*]
ignore_missing_imports = True

[mypy-celery.backends.redis.*]
ignore_missing_imports = True

[mypy-cgi.*]
ignore_missing_imports = True

[mypy-google.cloud.storage.*]
ignore_missing_imports = True

[mypy-forcediphttpsadapter.*]
ignore_missing_imports = True

[mypy-IPython.*]
ignore_missing_imports = True

[mypy-packaging_legacy.*]
ignore_missing_imports = True

[mypy-paginate.*]
ignore_missing_imports = True

[mypy-paginate_sqlalchemy.*]
ignore_missing_imports = True

[mypy-premailer.*]
ignore_missing_imports = True

[mypy-pymacaroons.*]
ignore_missing_imports = True

[mypy-pyramid.*]
ignore_missing_imports = True

[mypy-pyramid_jinja2.*]
ignore_missing_imports = True

[mypy-pyramid_mailer.*]
ignore_missing_imports = True

[mypy-pyramid_retry.*]
ignore_missing_imports = True

[mypy-pyramid_rpc.*]
ignore_missing_imports = True

[mypy-pyqrcode.*]
ignore_missing_imports = True

[mypy-requests_aws4auth.*]
ignore_missing_imports = True

[mypy-rfc3986.*]
ignore_missing_imports = True

[mypy-transaction.*]
ignore_missing_imports = True

[mypy-venusian.*]
ignore_missing_imports = True

[mypy-whitenoise.*]
ignore_missing_imports = True

[mypy-zope.sqlalchemy.*]
ignore_missing_imports = True