cache-dir = ".cache/ruff"
target-version = "py314"

[lint]
# Enable ALL lints by default, then opt out of ones we don't want to use so that we
# pick up new lints by default when we upgrade and if they fail, we can make a decision
# about whether to ignore it or fix it.
select = ["ALL"]
ignore = [
  "RUF012",  # This lint triggers in cases where it's impossible for us to fix it
  "TC",     # The circular imports in our db models break this
  "PIE807", # Turns `lambda: dict()` into just `dict`, which changes the signature
  "FIX",    # We regularly leave TODO comments in the code, which this rejects
  "TD",     # This wants TODO comments to have author and link, which we don't do
  "ERA",    # This has a REALLY high false positive rate
  "ANN",    # Requires typing annotations, which has almost 15k errors for us
  "S101",   # We use assert in the test suite, but more importantly for type narrowing
  "FBT",    # Rejects boolean params that change function behavior, requires API changes
  "B019",   # We have some uses of this, we should probably fix them
  "B904",   # Rejects raise without from, requires manual review
  "A",      # Rejects shadowing builtins, which we do a bit and would need closer review
  "SLF",    # Rejects using _private items, would need careful review to add
  "DTZ",    # Prevents using naive datetimes, probably useful, but needs manual review
  "TRY",    # Would require reworking some of our exceptions to make this work
  "EM",     # Would require reworking some of our exceptions to make this work
  "PLR0911",# Too many return statements; I'm suspect on the value of the "too many X" rules
  "PLR0912",# Too many branches; I'm suspect on the value of the "too many X" rules
  "PLR0913",# Too many arguments; I'm suspect on the value of the "too many X" rules
  "PLR0915",# Too many statements; I'm suspect on the value of the "too many X" rules
  "PLR2004",# We use a lot of magic values, maybe we shouldn't but for now allow it
  "PLW1641",# We don't need every object to implement __hash__
  "PTH",    # Tries to enforce pathlib, but most of our paths are abstract urls/keys
  "ARG",    # Rejects unused arguments, but we have to have them in a lot of places
  "C90",    # Enforces mccabe complexity, adding would require refactoring
  "D",      # Requires doc strings, super high error rate for us and not much value
  "COM812", # Incompatible with the formatter, no idea why this even exists
  "COM819", # Redundant with the formatter, also no idea why this even exists
]

[lint.per-file-ignores]
# N805: zope.interface definitions look like classes, but are not
"interfaces.py" = ["N805"]

# INP001: Our migrations are scripts not files that are part of a package
"warehouse/migrations/**/*.py" = ["INP001"]

# The warehouse cli can use print to give feedback to the user.
# The warehouse cli also defers imports on purpose.
"warehouse/cli/**/*.py" = ["T201", "PLC0415"]

# INP001: These are just scripts as well.
# T201: These scripts/helpers are fine to call print
"bin/*.py" = ["INP001", "T201"]
"dev/*.py" = ["INP001", "T201"]
"docs/**/*.py" = ["INP001"]
".github/codeql/custom-queries/python/**/*.py" = ["INP001"]

# PT009: These files use a lot of custom assertion tools that trip up this detection.
"tests/unit/email/test_init.py" = ["PT009"]
"tests/unit/email/test_services.py" = ["PT009"]
"tests/unit/test_views.py" = ["PT009"]

"tests/**/*.py" = [
  "TID252", # Pretty much all of our tests use relative imports
  "S104",   # Tests use 0.0.0.0 as a sentinel value sometimes
  "S105",   # Tests aren't used in production and can use hardcoded pws for tests
  "S106",   # Tests aren't used in production and can use hardcoded pws for tests
  "S108",   # Tests use hardcoded tmp paths that get stubbed out
  "S303",   # Strength of the hash functions used in tests doesn't matter
  "S311",   # Tests don't need cryptographically strong randomness
  "S324"    # Strength of the hash functions used in tests doesn't matter
]

[lint.isort]
combine-as-imports = true
lines-between-types = 1
# Even though `cgi` isn't a stdlib module anymore, treat it as one for now
extra-standard-library = ["cgi"]

[lint.pep8-naming]
classmethod-decorators = [
  # Allow SQLAlchemy's dynamic decorators, like `@field.expression`, to trigger class
  # method treatment.
  "declared_attr",
  "expression",
  "comparator",
]

[lint.flake8-tidy-imports.banned-api]
"urllib.parse.urlparse".msg = "Prefer `urllib3.util.parse_url` over `urllib.parse.urlparse`"
